# Content related GraphQL types

type Post {
  id: ID!
  content: String!
  author: User!
  createdAt: String!
  media: [Media!]!
  interaction: Interaction!
  comments(first: Int!, after: String): CommentConnection
}

type Comment {
  id: ID!
  content: String!
  author: User!
  createdAt: String!
  interaction: Interaction!
}

input CreatePostInput {
  content: String!
  mediaUrls: [String!]
  replyTo: ID
}

input CreateCommentInput {
  content: String!
  postId: ID!
}

type Media {
  id: ID!
  url: String!
  type: MediaType!
}

enum MediaType {
  IMAGE
  VIDEO
}

type PageInfo {
  hasNextPage: Boolean!
  endCursor: String
}

type PostEdge {
  node: Post!
  cursor: String!
}

type PostConnection {
  edges: [PostEdge!]!
  pageInfo: PageInfo!
}

type CommentEdge {
  node: Comment!
  cursor: String!
}

type CommentConnection {
  edges: [CommentEdge!]!
  pageInfo: PageInfo!
}
