# Content related GraphQL types

type Post {
  id: ID!
  content: String!
  author: User!
  createdAt: String!
  media: [Media!]!
  interaction: Interaction!
  replies(first: Int!, after: String): ReplyConnection
}

type Reply {
  id: ID!
  content: String!
  author: User!
  createdAt: String!
  interaction: Interaction!
}

input CreatePostInput {
  content: String!
  mediaUrls: [String!]
  replyTo: ID
}

input CreateReplyInput {
  content: String!
  postId: ID!
}

type Media {
  id: ID!
  url: String!
  type: MediaType!
}

enum MediaType {
  IMAGE
  VIDEO
}

type PageInfo {
  hasNextPage: Boolean!
  endCursor: String
}

type PostEdge {
  node: Post!
  cursor: String!
}

type PostConnection {
  edges: [PostEdge!]!
  pageInfo: PageInfo!
}

type ReplyEdge {
  node: Reply!
  cursor: String!
}

type ReplyConnection {
  edges: [ReplyEdge!]!
  pageInfo: PageInfo!
}
