// GraphQL generated types
// This is a placeholder file - in a real implementation, this would be generated by graphql-codegen

export interface User {
  id: string;
  username: string;
  displayName?: string;
  bio?: string;
  location?: string;
  website?: string;
  avatarUrl?: string;
  bannerUrl?: string;
  followersCount: number;
  followingCount: number;
  isFollowing?: boolean;
  isVerified?: boolean;
  createdAt: string;
}

export interface Post {
  id: string;
  content: string;
  author: User;
  createdAt: string;
  media: Media[];
  interaction: Interaction;
}


export interface Media {
  id: string;
  url: string;
  type: MediaType;
}

export enum MediaType {
  IMAGE = "IMAGE",
  VIDEO = "VIDEO"
}

export interface Interaction {
  isLiked: boolean;
  isBookmarked: boolean;
  isReposted: boolean;
  likeCount: number;
  commentCount: number;
  repostCount: number;
}

export interface PageInfo {
  hasNextPage: boolean;
  endCursor?: string;
}

export interface PostConnection {
  edges: PostEdge[];
  pageInfo: PageInfo;
}

export interface PostEdge {
  node: Post;
  cursor: string;
}


export interface AuthPayload {
  token: string;
  user: User;
}

export interface Notification {
  id: string;
  type: NotificationType;
  actor: User;
  entity: any;
  read: boolean;
  createdAt: string;
}

export enum NotificationType {
  LIKE = "LIKE",
  COMMENT = "COMMENT",
  FOLLOW = "FOLLOW",
  REPOST = "REPOST",
  BOOKMARK = "BOOKMARK"
}

export interface Conversation {
  id: string;
  participants: User[];
  lastMessage?: Message;
  unreadCount: number;
  createdAt: string;
}

export interface Message {
  id: string;
  conversationId: string;
  sender: User;
  content: string;
  media?: Media;
  read: boolean;
  createdAt: string;
}
