// GraphQL generated types
// This is a placeholder file - in a real implementation, this would be generated by graphql-codegen

export interface User {
  id: string;
  username: string;
  displayName?: string;
  bio?: string;
  location?: string;
  website?: string;
  avatarUrl?: string;
  bannerUrl?: string;
  followersCount: number;
  followingCount: number;
  isFollowing?: boolean;
  isVerified?: boolean;
  createdAt: string;
}

export interface Post {
  id: string;
  content: string;
  author: User;
  parentId?: string;
  rootId?: string;
  isReply: boolean;
  replyLevel: number;
  createdAt: string;
  updatedAt: string;
  media: Media[];
  interaction: Interaction;
}

export interface PostStats {
  likeCount: number;
  replyCount: number;
  repostCount: number;
  viewCount: number;
}

export interface Reply {
  id: string;
  content: string;
  author: User;
  createdAt: string;
  interaction: Interaction;
}

// 媒体版本信息
export interface MediaVariant {
  url: string;
  width: number;
  height: number;
  size: number;
}

// 多版本媒体信息
export interface MediaVariants {
  thumbnail?: MediaVariant; // 缩略图 (150px)
  small?: MediaVariant;     // 小图 (300px)
  medium?: MediaVariant;    // 中图 (600px)
  large?: MediaVariant;     // 大图 (1200px)
  original?: MediaVariant;  // 原图
  // 视频特有
  preview?: MediaVariant;   // 视频预览图
  lowRes?: MediaVariant;    // 低分辨率视频 (240p)
  midRes?: MediaVariant;    // 中分辨率视频 (480p)
  highRes?: MediaVariant;   // 高分辨率视频 (720p)
}

export interface Media {
  id: string;
  url: string; // 保留向后兼容
  type: MediaType;
  mimeType?: string;
  width?: number;
  height?: number;
  duration?: number; // 视频时长(秒)
  variants?: MediaVariants; // 多版本URL
  altText?: string;
}

export enum MediaType {
  IMAGE = "IMAGE",
  VIDEO = "VIDEO"
}

export interface Interaction {
  isLiked: boolean;
  isBookmarked: boolean;
  isReposted: boolean;
  likeCount: number;
  replyCount: number;
  repostCount: number;
  viewCount: number;
}

export interface PageInfo {
  hasNextPage: boolean;
  endCursor?: string;
}

export interface PostConnection {
  edges: PostEdge[];
  pageInfo: PageInfo;
}

export interface PostEdge {
  node: Post;
  cursor: string;
}


export interface AuthPayload {
  token: string;
  user: User;
}

export interface Notification {
  id: string;
  type: NotificationType;
  actor: User;
  entity: any;
  read: boolean;
  createdAt: string;
}

export enum NotificationType {
  LIKE = "LIKE",
  REPLY = "REPLY",
  FOLLOW = "FOLLOW",
  REPOST = "REPOST",
  BOOKMARK = "BOOKMARK"
}

export interface Conversation {
  id: string;
  participants: User[];
  lastMessage?: Message;
  unreadCount: number;
  createdAt: string;
}

export interface Message {
  id: string;
  conversationId: string;
  sender: User;
  content: string;
  media?: Media;
  read: boolean;
  createdAt: string;
}
